version: '3.8'

services:
  app:
    image: 2b4cba85892a/dbm:v3
    ports:
      - "5000:5000"
    volumes:
      - mysql_logs:/var/log/mysql
    environment:
      - FLASK_DEBUG=1
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
    container_name: itshield_app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: itshield_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: itshield
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    command: --general-log=1 --general_log_file=/var/log/mysql/mysql.log
    networks:
      - app-network

volumes:
  db_data:
  mysql_logs:

networks:
  app-network:
    driver: bridge