services:
  app:
    build:
      context: DBM
    ports:
      - "5000:5000"
    volumes:
      - ./DBM:/app
      - mysql_logs:/var/log/mysql
      - postgres_logs:/var/log/postgres
    environment:
      - FLASK_DEBUG=1
      - MYSQL_HOST=mysql_db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - POSTGRES_HOST=postgres_db
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
    container_name: itshield_app
    depends_on:
      - mysql_db
      - postgres_db
    networks:
      - app-network

  mysql_db:
    image: mysql:8.0
    container_name: itshield_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: employees
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    command: --general-log=1 --general_log_file=/var/log/mysql/mysql.log
    networks:
      - app-network

  postgres_db:
    image: postgres:13
    container_name: itshield_postgres_db
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: itshield
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgres
    command: >
      -c log_statement=all
      -c log_destination=stderr
      -c logging_collector=on
      -c log_directory=/var/log/postgres
      -c log_filename=postgres.log
    depends_on:
      - postgres_init
    networks:
      - app-network

  postgres_init:
    image: postgres:13
    container_name: itshield_postgres_init
    volumes:
      - postgres_logs:/var/log/postgres
    command: >
      /bin/sh -c "
        mkdir -p /var/log/postgres &&
        chown 999:999 /var/log/postgres &&
        chmod 775 /var/log/postgres
      "
    networks:
      - app-network

volumes:
  mysql_data:
  postgres_data:
  mysql_logs:
  postgres_logs:

networks:
  app-network:
    driver: bridge